name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Fix libudev error in Conda environment
      run: |
        LIB_PATH=$(conda run -n visualizer which pip | rev | cut -d/ -f3- | rev)/lib
        ln -sf $LIB_PATH/libudev.so.1 $LIB_PATH/libudev.so.0 || echo "libudev.so.0 already exists"

    - name: Configure CMake
      run: |
        mkdir -p ${{github.workspace}}/build
        conda run -n visualizer cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: conda run -n visualizer cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: conda run -n visualizer ctest -C ${{env.BUILD_TYPE}}
